# Generated by Django 3.0.5 on 2020-12-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201216_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
