# Generated by Django 3.0.5 on 2020-12-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Index',
        ),
    ]
