# Generated by Django 3.0.5 on 2020-12-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201217_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
