# Generated by Django 3.1.3 on 2020-12-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201217_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='beds',
            name='image',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
        migrations.AddField(
            model_name='chest',
            name='image',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
        migrations.AddField(
            model_name='dining',
            name='image',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
        migrations.AddField(
            model_name='dressing',
            name='image',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
        migrations.AddField(
            model_name='sofa',
            name='image',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
        migrations.AddField(
            model_name='wardrobs',
            name='image',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='beds',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='beds',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beds',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
