# Generated by Django 3.0.5 on 2020-12-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sofa_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sofa',
            name='image',
        ),
    ]
