# Generated by Django 3.0.5 on 2021-01-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201218_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image1', models.ImageField(default='', upload_to='media/image')),
                ('image2', models.ImageField(default='', upload_to='media/image')),
                ('image3', models.ImageField(default='', upload_to='media/image')),
            ],
        ),
    ]
