# Generated by Django 3.1.3 on 2020-12-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201218_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofa',
            name='image',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
    ]
