<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-12-18 14:36
=======
# Generated by Django 3.0.5 on 2020-12-18 04:11
>>>>>>> 66d44186ab36a57484b81d864997e4249d30458b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('home', '0010_auto_20201218_1434'),
=======
        ('home', '0010_remove_sofa_image'),
>>>>>>> 66d44186ab36a57484b81d864997e4249d30458b
    ]

    operations = [
        migrations.AddField(
            model_name='sofa',
            name='image',
<<<<<<< HEAD
            field=models.ImageField(default='', upload_to='media/image'),
=======
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
>>>>>>> 66d44186ab36a57484b81d864997e4249d30458b
        ),
    ]
