# Generated by Django 3.0.5 on 2020-12-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_sofa_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofa',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
