# Generated by Django 3.0.5 on 2020-12-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sofa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofa',
            name='image',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
