# Generated by Django 3.0.5 on 2020-12-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201218_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sofa',
            name='image',
        ),
    ]
